/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignInImport } from './routes/signIn'
import { Route as ProtectedImport } from './routes/_protected'
import { Route as InsighsNavigationIndexImport } from './routes/InsighsNavigation/index'
import { Route as ProtectedLayoutImport } from './routes/_protected/_layout'
import { Route as ProtectedLayoutSurveysImport } from './routes/_protected/_layout/surveys'
import { Route as ProtectedLayoutSettingsImport } from './routes/_protected/_layout/settings'

// Create Virtual Routes

const SignUpLazyImport = createFileRoute('/signUp')()
const LandingPageLazyImport = createFileRoute('/landingPage')()
const ProtectedLayoutIndexLazyImport = createFileRoute('/_protected/_layout/')()

// Create/Update Routes

const SignUpLazyRoute = SignUpLazyImport.update({
  path: '/signUp',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signUp.lazy').then((d) => d.Route))

const LandingPageLazyRoute = LandingPageLazyImport.update({
  path: '/landingPage',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/landingPage.lazy').then((d) => d.Route))

const SignInRoute = SignInImport.update({
  path: '/signIn',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedRoute = ProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const InsighsNavigationIndexRoute = InsighsNavigationIndexImport.update({
  path: '/InsighsNavigation/',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedLayoutRoute = ProtectedLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedLayoutIndexLazyRoute = ProtectedLayoutIndexLazyImport.update({
  path: '/',
  getParentRoute: () => ProtectedLayoutRoute,
} as any).lazy(() =>
  import('./routes/_protected/_layout/index.lazy').then((d) => d.Route),
)

const ProtectedLayoutSurveysRoute = ProtectedLayoutSurveysImport.update({
  path: '/surveys',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

const ProtectedLayoutSettingsRoute = ProtectedLayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/signIn': {
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/landingPage': {
      preLoaderRoute: typeof LandingPageLazyImport
      parentRoute: typeof rootRoute
    }
    '/signUp': {
      preLoaderRoute: typeof SignUpLazyImport
      parentRoute: typeof rootRoute
    }
    '/_protected/_layout': {
      preLoaderRoute: typeof ProtectedLayoutImport
      parentRoute: typeof ProtectedImport
    }
    '/InsighsNavigation/': {
      preLoaderRoute: typeof InsighsNavigationIndexImport
      parentRoute: typeof rootRoute
    }
    '/_protected/_layout/settings': {
      preLoaderRoute: typeof ProtectedLayoutSettingsImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protected/_layout/surveys': {
      preLoaderRoute: typeof ProtectedLayoutSurveysImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protected/_layout/': {
      preLoaderRoute: typeof ProtectedLayoutIndexLazyImport
      parentRoute: typeof ProtectedLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  ProtectedRoute.addChildren([
    ProtectedLayoutRoute.addChildren([
      ProtectedLayoutSettingsRoute,
      ProtectedLayoutSurveysRoute,
      ProtectedLayoutIndexLazyRoute,
    ]),
  ]),
  SignInRoute,
  LandingPageLazyRoute,
  SignUpLazyRoute,
  InsighsNavigationIndexRoute,
])

/* prettier-ignore-end */
